create type public.user_account_status as enum ('active', 'suspended');

create table public.user_admin_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status public.user_account_status not null default 'active',
  reason text not null default '' check (char_length(reason) <= 500),
  suspended_until timestamptz,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null,
  check (
    (status = 'active' and suspended_until is null)
    or status = 'suspended'
  )
);

create table public.admin_user_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  action text not null check (char_length(action) between 3 and 80),
  reason text not null default '' check (char_length(reason) <= 500),
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index admin_user_audit_target_idx
on public.admin_user_audit_log (target_user_id, created_at desc);

alter table public.user_admin_state enable row level security;
alter table public.admin_user_audit_log enable row level security;

revoke all on public.user_admin_state, public.admin_user_audit_log from anon, authenticated;
revoke all on sequence public.admin_user_audit_log_id_seq from anon, authenticated;

create function public.get_admin_users(
  p_query text default '',
  p_status text default 'all',
  p_limit integer default 30,
  p_offset integer default 0
)
returns table (
  id uuid,
  email text,
  handle text,
  display_name text,
  bio text,
  avatar_url text,
  account_status text,
  is_admin boolean,
  email_confirmed_at timestamptz,
  last_sign_in_at timestamptz,
  created_at timestamptz,
  deck_count bigint,
  post_count bigint,
  organization_count bigint,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_status not in ('all', 'active', 'pending', 'suspended') then
    raise exception 'Invalid account status';
  end if;

  return query
  with users_with_status as (
    select
      auth_user.id as id,
      coalesce(auth_user.email, '')::text as email,
      profile.handle::text as handle,
      profile.display_name as display_name,
      profile.bio as bio,
      profile.avatar_url as avatar_url,
      case
        when coalesce(state.status = 'suspended', false)
          or auth_user.banned_until > now() then 'suspended'
        when auth_user.email_confirmed_at is null then 'pending'
        else 'active'
      end::text as account_status,
      exists (
        select 1 from public.user_roles membership
        where membership.user_id = auth_user.id and membership.role = 'admin'
      ) as is_admin,
      auth_user.email_confirmed_at as email_confirmed_at,
      auth_user.last_sign_in_at as last_sign_in_at,
      auth_user.created_at as created_at,
      (select count(*) from public.decks deck where deck.owner_id = auth_user.id) as deck_count,
      (select count(*) from public.posts post where post.author_id = auth_user.id) as post_count,
      (select count(*) from public.organization_members membership where membership.user_id = auth_user.id) as organization_count
    from auth.users auth_user
    join public.profiles profile on profile.id = auth_user.id
    left join public.user_admin_state state on state.user_id = auth_user.id
  ), filtered as (
    select * from users_with_status user_row
    where (
      trim(coalesce(p_query, '')) = ''
      or user_row.email ilike '%' || trim(p_query) || '%'
      or user_row.handle ilike '%' || trim(p_query) || '%'
      or user_row.display_name ilike '%' || trim(p_query) || '%'
    )
      and (p_status = 'all' or user_row.account_status = p_status)
  )
  select filtered.*, count(*) over() as total_count
  from filtered
  order by filtered.created_at desc, filtered.id
  limit least(greatest(p_limit, 1), 100)
  offset greatest(p_offset, 0);
end;
$$;

create function public.admin_update_user_profile(
  p_user_id uuid,
  p_handle text,
  p_display_name text,
  p_bio text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := (select auth.uid());
  previous_profile jsonb;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  select jsonb_build_object(
    'handle', profile.handle::text,
    'display_name', profile.display_name,
    'bio', profile.bio
  ) into previous_profile
  from public.profiles profile where profile.id = p_user_id for update;
  if previous_profile is null then raise exception 'User not found'; end if;

  update public.profiles
  set handle = trim(p_handle), display_name = trim(p_display_name), bio = trim(coalesce(p_bio, ''))
  where profiles.id = p_user_id;

  insert into public.admin_user_audit_log (actor_id, target_user_id, action, metadata)
  values (
    actor,
    p_user_id,
    'profile_updated',
    jsonb_build_object(
      'before', previous_profile,
      'after', jsonb_build_object('handle', trim(p_handle), 'display_name', trim(p_display_name), 'bio', trim(coalesce(p_bio, '')))
    )
  );
end;
$$;

create function public.admin_set_user_role(p_user_id uuid, p_enabled boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := (select auth.uid());
  role_count integer;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if not exists (select 1 from auth.users auth_user where auth_user.id = p_user_id) then
    raise exception 'User not found';
  end if;

  if p_enabled then
    insert into public.user_roles (user_id, role, granted_by)
    values (p_user_id, 'admin', actor)
    on conflict do nothing;
  else
    select count(*) into role_count from public.user_roles where role = 'admin';
    if exists (
      select 1 from public.user_roles where user_id = p_user_id and role = 'admin'
    ) and role_count <= 1 then
      raise exception 'The last administrator cannot be removed';
    end if;
    delete from public.user_roles where user_id = p_user_id and role = 'admin';
  end if;

  insert into public.admin_user_audit_log (actor_id, target_user_id, action, metadata)
  values (actor, p_user_id, case when p_enabled then 'admin_role_granted' else 'admin_role_revoked' end, '{}');
end;
$$;

create function public.admin_set_user_state(
  p_user_id uuid,
  p_status public.user_account_status,
  p_reason text default ''
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := (select auth.uid());
  admin_count integer;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if not exists (select 1 from auth.users auth_user where auth_user.id = p_user_id) then
    raise exception 'User not found';
  end if;
  if p_status = 'suspended' and p_user_id = actor then
    raise exception 'Administrators cannot suspend themselves';
  end if;
  if p_status = 'suspended' and exists (
    select 1 from public.user_roles where user_id = p_user_id and role = 'admin'
  ) then
    select count(*) into admin_count from public.user_roles where role = 'admin';
    if admin_count <= 1 then raise exception 'The last administrator cannot be suspended'; end if;
  end if;

  insert into public.user_admin_state (user_id, status, reason, suspended_until, changed_by)
  values (
    p_user_id,
    p_status,
    trim(coalesce(p_reason, '')),
    case when p_status = 'suspended' then now() + interval '100 years' else null end,
    actor
  )
  on conflict (user_id) do update
  set status = excluded.status,
      reason = excluded.reason,
      suspended_until = excluded.suspended_until,
      changed_at = now(),
      changed_by = excluded.changed_by;

  insert into public.admin_user_audit_log (actor_id, target_user_id, action, reason)
  values (
    actor,
    p_user_id,
    case when p_status = 'suspended' then 'user_suspended' else 'user_reactivated' end,
    trim(coalesce(p_reason, ''))
  );
end;
$$;

create function public.admin_log_user_invited(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  insert into public.admin_user_audit_log (actor_id, target_user_id, action)
  values ((select auth.uid()), p_user_id, 'user_invited');
end;
$$;

create function public.admin_assert_user_deletable(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := (select auth.uid());
  admin_count integer;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_user_id = actor then raise exception 'Administrators cannot delete themselves'; end if;
  if not exists (select 1 from auth.users auth_user where auth_user.id = p_user_id) then
    raise exception 'User not found';
  end if;
  if exists (select 1 from public.posts where author_id = p_user_id)
    or exists (select 1 from public.decks where owner_id = p_user_id)
    or exists (select 1 from public.organizations where created_by = p_user_id)
    or exists (
      select 1 from public.organization_members
      where user_id = p_user_id and role = 'owner'
    ) then
    raise exception 'User still owns content';
  end if;
  if exists (select 1 from public.user_roles where user_id = p_user_id and role = 'admin') then
    select count(*) into admin_count from public.user_roles where role = 'admin';
    if admin_count <= 1 then raise exception 'The last administrator cannot be deleted'; end if;
  end if;

  insert into public.admin_user_audit_log (actor_id, target_user_id, action, metadata)
  values (actor, p_user_id, 'user_deletion_requested', jsonb_build_object('user_id', p_user_id));
end;
$$;

revoke all on function public.get_admin_users(text, text, integer, integer) from public, anon;
revoke all on function public.admin_update_user_profile(uuid, text, text, text) from public, anon;
revoke all on function public.admin_set_user_role(uuid, boolean) from public, anon;
revoke all on function public.admin_set_user_state(uuid, public.user_account_status, text) from public, anon;
revoke all on function public.admin_log_user_invited(uuid) from public, anon;
revoke all on function public.admin_assert_user_deletable(uuid) from public, anon;

grant execute on function public.get_admin_users(text, text, integer, integer) to authenticated;
grant execute on function public.admin_update_user_profile(uuid, text, text, text) to authenticated;
grant execute on function public.admin_set_user_role(uuid, boolean) to authenticated;
grant execute on function public.admin_set_user_state(uuid, public.user_account_status, text) to authenticated;
grant execute on function public.admin_log_user_invited(uuid) to authenticated;
grant execute on function public.admin_assert_user_deletable(uuid) to authenticated;
