alter table public.organizations
  add column archived_by uuid references auth.users(id) on delete set null,
  add column archive_reason text not null default '' check (char_length(archive_reason) <= 500);

create table public.admin_organization_audit_log (
  id bigint generated by default as identity primary key,
  organization_id uuid not null,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null check (char_length(action) between 3 and 80),
  reason text not null default '' check (char_length(reason) <= 500),
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index admin_organization_audit_idx
on public.admin_organization_audit_log (organization_id, created_at desc);

alter table public.admin_organization_audit_log enable row level security;
revoke all on public.admin_organization_audit_log from anon, authenticated;
revoke all on sequence public.admin_organization_audit_log_id_seq from anon, authenticated;

create policy "admins view archived organizations"
on public.organizations for select to authenticated
using (public.is_admin());

create function public.get_admin_organizations(
  p_query text default '',
  p_status text default 'all',
  p_access text default 'all',
  p_limit integer default 30,
  p_offset integer default 0
)
returns table (
  id uuid,
  slug text,
  name text,
  kind text,
  access text,
  description text,
  website_url text,
  location text,
  formats text[],
  creator_handle text,
  owner_handles text,
  member_count bigint,
  pending_request_count bigint,
  topic_count bigint,
  announcement_count bigint,
  created_at timestamptz,
  updated_at timestamptz,
  archived_at timestamptz,
  archive_reason text,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_status not in ('all', 'active', 'archived') then raise exception 'Invalid organization status'; end if;
  if p_access not in ('all', 'public', 'private') then raise exception 'Invalid organization access'; end if;

  return query
  with organization_rows as (
    select
      organization.id as id,
      organization.slug::text as slug,
      organization.name as name,
      organization.kind::text as kind,
      organization.access::text as access,
      organization.description as description,
      organization.website_url as website_url,
      organization.location as location,
      organization.formats as formats,
      coalesce(creator.handle::text, '') as creator_handle,
      coalesce((
        select string_agg(owner_profile.handle::text, ', ' order by owner_profile.handle::text)
        from public.organization_members owner_membership
        join public.profiles owner_profile on owner_profile.id = owner_membership.user_id
        where owner_membership.organization_id = organization.id and owner_membership.role = 'owner'
      ), '')::text as owner_handles,
      (select count(*) from public.organization_members membership where membership.organization_id = organization.id) as member_count,
      (select count(*) from public.organization_join_requests request where request.organization_id = organization.id and request.status = 'pending') as pending_request_count,
      (select count(*) from public.organization_forum_topics topic where topic.organization_id = organization.id) as topic_count,
      (select count(*) from public.organization_announcements announcement where announcement.organization_id = organization.id) as announcement_count,
      organization.created_at as created_at,
      organization.updated_at as updated_at,
      organization.archived_at as archived_at,
      organization.archive_reason as archive_reason
    from public.organizations organization
    left join public.profiles creator on creator.id = organization.created_by
  ), filtered as (
    select * from organization_rows organization_row
    where (
      trim(coalesce(p_query, '')) = ''
      or organization_row.name ilike '%' || trim(p_query) || '%'
      or organization_row.slug ilike '%' || trim(p_query) || '%'
      or organization_row.owner_handles ilike '%' || trim(p_query) || '%'
      or organization_row.creator_handle ilike '%' || trim(p_query) || '%'
    )
      and (p_status = 'all' or (p_status = 'active' and organization_row.archived_at is null)
        or (p_status = 'archived' and organization_row.archived_at is not null))
      and (p_access = 'all' or organization_row.access = p_access)
  )
  select filtered.*, count(*) over() as total_count
  from filtered
  order by filtered.archived_at nulls first, filtered.created_at desc, filtered.id
  limit least(greatest(p_limit, 1), 100)
  offset greatest(p_offset, 0);
end;
$$;

create function public.admin_create_organization(
  p_owner_id uuid,
  p_name text,
  p_slug text,
  p_kind public.organization_kind,
  p_access public.organization_access,
  p_description text default '',
  p_website_url text default null,
  p_location text default null,
  p_formats text[] default '{}'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := (select auth.uid());
  organization_id uuid;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if not exists (select 1 from public.profiles where id = p_owner_id) then raise exception 'Owner not found'; end if;

  insert into public.organizations (name, slug, kind, access, description, website_url, location, formats, created_by)
  values (
    trim(p_name), lower(trim(p_slug)), p_kind, p_access, trim(coalesce(p_description, '')),
    nullif(trim(coalesce(p_website_url, '')), ''), nullif(trim(coalesce(p_location, '')), ''), coalesce(p_formats, '{}'), p_owner_id
  ) returning organizations.id into organization_id;

  insert into public.organization_members (organization_id, user_id, role, invited_by)
  values (organization_id, p_owner_id, 'owner', actor);
  insert into public.organization_audit_log (organization_id, actor_id, action, target_user_id)
  values (organization_id, actor, 'organization_created_by_platform_admin', p_owner_id);
  insert into public.admin_organization_audit_log (organization_id, actor_id, action, metadata)
  values (organization_id, actor, 'organization_created', jsonb_build_object('owner_id', p_owner_id));
  return organization_id;
end;
$$;

create function public.admin_update_organization(
  p_organization_id uuid,
  p_name text,
  p_kind public.organization_kind,
  p_access public.organization_access,
  p_description text,
  p_website_url text,
  p_location text,
  p_formats text[]
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := (select auth.uid());
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  update public.organizations
  set name = trim(p_name), kind = p_kind, access = p_access,
      description = trim(coalesce(p_description, '')),
      website_url = nullif(trim(coalesce(p_website_url, '')), ''),
      location = nullif(trim(coalesce(p_location, '')), ''),
      formats = coalesce(p_formats, '{}')
  where organizations.id = p_organization_id;
  if not found then raise exception 'Organization not found'; end if;

  insert into public.organization_audit_log (organization_id, actor_id, action)
  values (p_organization_id, actor, 'organization_updated_by_platform_admin');
  insert into public.admin_organization_audit_log (organization_id, actor_id, action)
  values (p_organization_id, actor, 'organization_updated');
end;
$$;

create function public.admin_add_organization_owner(p_organization_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := (select auth.uid());
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if not exists (select 1 from public.organizations where id = p_organization_id for update) then
    raise exception 'Organization not found';
  end if;
  if not exists (select 1 from public.profiles where id = p_user_id) then raise exception 'User not found'; end if;

  insert into public.organization_members (organization_id, user_id, role, invited_by)
  values (p_organization_id, p_user_id, 'owner', actor)
  on conflict (organization_id, user_id) do update set role = 'owner', invited_by = actor;
  insert into public.organization_audit_log (organization_id, actor_id, action, target_user_id)
  values (p_organization_id, actor, 'organization_owner_added_by_platform_admin', p_user_id);
  insert into public.admin_organization_audit_log (organization_id, actor_id, action, metadata)
  values (p_organization_id, actor, 'organization_owner_added', jsonb_build_object('owner_id', p_user_id));
end;
$$;

create function public.admin_set_organization_archived(
  p_organization_id uuid,
  p_archived boolean,
  p_reason text default ''
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := (select auth.uid());
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_archived and char_length(trim(coalesce(p_reason, ''))) < 3 then raise exception 'Archive reason required'; end if;

  update public.organizations
  set archived_at = case when p_archived then now() else null end,
      archived_by = case when p_archived then actor else null end,
      archive_reason = case when p_archived then trim(p_reason) else '' end
  where organizations.id = p_organization_id;
  if not found then raise exception 'Organization not found'; end if;

  insert into public.organization_audit_log (organization_id, actor_id, action, metadata)
  values (
    p_organization_id, actor,
    case when p_archived then 'organization_archived' else 'organization_restored' end,
    jsonb_build_object('reason', trim(coalesce(p_reason, '')))
  );
  insert into public.admin_organization_audit_log (organization_id, actor_id, action, reason)
  values (
    p_organization_id, actor,
    case when p_archived then 'organization_archived' else 'organization_restored' end,
    trim(coalesce(p_reason, ''))
  );
end;
$$;

create function public.delete_empty_organization(p_organization_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := (select auth.uid());
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if not exists (
    select 1 from public.organizations where id = p_organization_id and archived_at is not null for update
  ) then raise exception 'Organization must be archived'; end if;
  if exists (select 1 from public.organization_forum_topics where organization_id = p_organization_id)
    or exists (select 1 from public.organization_announcements where organization_id = p_organization_id)
    or exists (select 1 from public.organization_join_requests where organization_id = p_organization_id)
    or (select count(*) from public.organization_members where organization_id = p_organization_id) > 1 then
    raise exception 'Organization still has activity';
  end if;

  insert into public.admin_organization_audit_log (organization_id, actor_id, action)
  values (p_organization_id, actor, 'organization_deleted');
  delete from public.organizations where id = p_organization_id;
end;
$$;

-- Archived organizations remain readable to their members for historical context,
-- but no direct content write may succeed while the root aggregate is archived.
drop policy "members create organization topics" on public.organization_forum_topics;
create policy "members create organization topics" on public.organization_forum_topics for insert to authenticated
with check (
  author_id = (select auth.uid())
  and public.is_organization_member(organization_id)
  and exists (select 1 from public.organizations where id = organization_id and archived_at is null)
);

drop policy "authors update organization topics" on public.organization_forum_topics;
create policy "authors update organization topics" on public.organization_forum_topics for update to authenticated
using (author_id = (select auth.uid()) and status = 'published')
with check (
  author_id = (select auth.uid())
  and exists (select 1 from public.organizations where id = organization_id and archived_at is null)
);

drop policy "members create organization messages" on public.organization_forum_messages;
create policy "members create organization messages" on public.organization_forum_messages for insert to authenticated
with check (
  author_id = (select auth.uid()) and exists (
    select 1 from public.organization_forum_topics topic
    join public.organizations organization on organization.id = topic.organization_id
    where topic.id = topic_id and topic.status = 'published' and not topic.is_locked
      and organization.archived_at is null and public.is_organization_member(topic.organization_id)
  )
);

drop policy "authors update organization messages" on public.organization_forum_messages;
create policy "authors update organization messages" on public.organization_forum_messages for update to authenticated
using (author_id = (select auth.uid()) and status = 'published')
with check (
  author_id = (select auth.uid()) and exists (
    select 1 from public.organization_forum_topics topic
    join public.organizations organization on organization.id = topic.organization_id
    where topic.id = topic_id and organization.archived_at is null
  )
);

drop policy "organization admins create announcements" on public.organization_announcements;
create policy "organization admins create announcements" on public.organization_announcements for insert to authenticated
with check (
  author_id = (select auth.uid())
  and exists (select 1 from public.organizations where id = organization_id and archived_at is null)
  and (
    public.has_organization_role(organization_id, array['owner', 'admin']::public.organization_member_role[])
    or public.is_admin()
  )
);

drop policy "organization admins update announcements" on public.organization_announcements;
create policy "organization admins update announcements" on public.organization_announcements for update to authenticated
using (
  public.has_organization_role(organization_id, array['owner', 'admin']::public.organization_member_role[])
  or public.is_admin()
)
with check (
  exists (select 1 from public.organizations where id = organization_id and archived_at is null)
  and (
    public.has_organization_role(organization_id, array['owner', 'admin']::public.organization_member_role[])
    or public.is_admin()
  )
);

revoke all on function public.get_admin_organizations(text, text, text, integer, integer) from public, anon;
revoke all on function public.admin_create_organization(uuid, text, text, public.organization_kind, public.organization_access, text, text, text, text[]) from public, anon;
revoke all on function public.admin_update_organization(uuid, text, public.organization_kind, public.organization_access, text, text, text, text[]) from public, anon;
revoke all on function public.admin_add_organization_owner(uuid, uuid) from public, anon;
revoke all on function public.admin_set_organization_archived(uuid, boolean, text) from public, anon;
revoke all on function public.delete_empty_organization(uuid) from public, anon;

grant execute on function public.get_admin_organizations(text, text, text, integer, integer) to authenticated;
grant execute on function public.admin_create_organization(uuid, text, text, public.organization_kind, public.organization_access, text, text, text, text[]) to authenticated;
grant execute on function public.admin_update_organization(uuid, text, public.organization_kind, public.organization_access, text, text, text, text[]) to authenticated;
grant execute on function public.admin_add_organization_owner(uuid, uuid) to authenticated;
grant execute on function public.admin_set_organization_archived(uuid, boolean, text) to authenticated;
grant execute on function public.delete_empty_organization(uuid) to authenticated;
