create type public.deck_moderation_status as enum ('visible', 'hidden');

alter table public.decks
  add column moderation_status public.deck_moderation_status not null default 'visible',
  add column moderation_reason text not null default '' check (char_length(moderation_reason) <= 500),
  add column moderated_at timestamptz,
  add column moderated_by uuid references auth.users(id) on delete set null,
  add column archived_at timestamptz,
  add column archived_by uuid references auth.users(id) on delete set null,
  add column archive_reason text not null default '' check (char_length(archive_reason) <= 500);

-- Moderation and archive fields are only writable through the audited admin
-- functions below. Owners retain access to the metadata they already manage.
revoke update on public.decks from authenticated;
grant update (title, description, visibility) on public.decks to authenticated;

create table public.deck_admin_audit_log (
  id bigint generated by default as identity primary key,
  deck_id uuid references public.decks(id) on delete set null,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null check (char_length(action) between 3 and 80),
  reason text not null default '' check (char_length(reason) <= 500),
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index deck_admin_audit_deck_idx on public.deck_admin_audit_log (deck_id, created_at desc);
alter table public.deck_admin_audit_log enable row level security;
revoke all on public.deck_admin_audit_log from anon, authenticated;
revoke all on sequence public.deck_admin_audit_log_id_seq from anon, authenticated;

drop policy "visible decks can be read" on public.decks;
create policy "visible decks can be read" on public.decks for select using (
  owner_id = (select auth.uid())
  or (
    moderation_status = 'visible' and archived_at is null
    and visibility in ('public', 'unlisted')
  )
);
create policy "admins read every deck" on public.decks for select to authenticated
using (public.is_admin());

drop policy "visible deck versions can be read" on public.deck_versions;
create policy "visible deck versions can be read" on public.deck_versions for select using (
  exists (
    select 1 from public.decks
    where decks.id = deck_versions.deck_id and (
      decks.owner_id = (select auth.uid())
      or (
        decks.moderation_status = 'visible' and decks.archived_at is null
        and decks.visibility in ('public', 'unlisted')
      )
    )
  )
);
create policy "admins read every deck version" on public.deck_versions for select to authenticated
using (public.is_admin());

drop policy "visible deck cards can be read" on public.deck_cards;
create policy "visible deck cards can be read" on public.deck_cards for select using (
  exists (
    select 1 from public.deck_versions
    join public.decks on decks.id = deck_versions.deck_id
    where deck_versions.id = deck_cards.deck_version_id and (
      decks.owner_id = (select auth.uid())
      or (
        decks.moderation_status = 'visible' and decks.archived_at is null
        and decks.visibility in ('public', 'unlisted')
      )
    )
  )
);
create policy "admins read every deck card" on public.deck_cards for select to authenticated
using (public.is_admin());

drop policy "owners create deck versions" on public.deck_versions;
create policy "owners create deck versions" on public.deck_versions for insert to authenticated
with check (exists (
  select 1 from public.decks
  where decks.id = deck_id and decks.owner_id = (select auth.uid()) and decks.archived_at is null
));

drop policy "owners create deck cards" on public.deck_cards;
create policy "owners create deck cards" on public.deck_cards for insert to authenticated
with check (
  exists (
    select 1 from public.deck_versions
    join public.decks on decks.id = deck_versions.deck_id
    where deck_versions.id = deck_version_id
      and decks.owner_id = (select auth.uid()) and decks.archived_at is null
  )
);

create function public.validate_deck_card_payload(p_format text, p_cards jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  mainboard_count integer;
  commander_count integer;
  format_rule public.formats%rowtype;
begin
  if jsonb_typeof(p_cards) <> 'array' or jsonb_array_length(p_cards) = 0 or jsonb_array_length(p_cards) > 500 then
    raise exception 'Invalid card count';
  end if;
  select * into format_rule from public.formats where slug = p_format and is_active;
  if not found then raise exception 'Unknown or archived format'; end if;
  if exists (
    select 1 from jsonb_array_elements(p_cards) card
    where (card ->> 'quantity')::integer not between 1 and 100
      or card ->> 'zone' not in ('commander', 'mainboard', 'sideboard', 'maybeboard')
  ) then raise exception 'Invalid card payload'; end if;

  select
    coalesce(sum((card ->> 'quantity')::integer) filter (where card ->> 'zone' = 'mainboard'), 0),
    coalesce(sum((card ->> 'quantity')::integer) filter (where card ->> 'zone' = 'commander'), 0)
  into mainboard_count, commander_count
  from jsonb_array_elements(p_cards) card;

  if mainboard_count < format_rule.mainboard_min
    or (format_rule.mainboard_max is not null and mainboard_count > format_rule.mainboard_max)
    or commander_count < format_rule.commander_min
    or commander_count > format_rule.commander_max
    or mainboard_count + commander_count < format_rule.total_min
    or (format_rule.total_max is not null and mainboard_count + commander_count > format_rule.total_max) then
    raise exception 'Deck does not satisfy format rules';
  end if;
end;
$$;

create function public.insert_deck_version_cards(p_version_id uuid, p_cards jsonb)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into public.deck_cards (
    deck_version_id, zone, quantity, oracle_id, scryfall_id,
    card_name, image_small_url, image_normal_url
  )
  select p_version_id, card.zone::public.deck_zone, card.quantity, card.oracle_id,
    card.scryfall_id, card.card_name, card.image_small_url, card.image_normal_url
  from jsonb_to_recordset(p_cards) as card(
    zone text, quantity smallint, oracle_id uuid, scryfall_id uuid,
    card_name text, image_small_url text, image_normal_url text
  );
$$;

create function public.get_admin_decks(
  p_query text default '',
  p_format text default 'all',
  p_state text default 'all',
  p_limit integer default 30,
  p_offset integer default 0
)
returns table (
  id uuid,
  owner_id uuid,
  owner_handle text,
  owner_name text,
  title text,
  format text,
  format_name text,
  description text,
  visibility text,
  moderation_status text,
  moderation_reason text,
  current_version integer,
  version_count bigint,
  total_cards bigint,
  post_count bigint,
  created_at timestamptz,
  updated_at timestamptz,
  archived_at timestamptz,
  archive_reason text,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_state not in ('all', 'active', 'hidden', 'archived') then raise exception 'Invalid deck state'; end if;

  return query
  with deck_rows as (
    select
      deck.id as id,
      deck.owner_id as owner_id,
      profile.handle::text as owner_handle,
      profile.display_name as owner_name,
      deck.title as title,
      deck.format as format,
      format.name as format_name,
      deck.description as description,
      deck.visibility::text as visibility,
      deck.moderation_status::text as moderation_status,
      deck.moderation_reason as moderation_reason,
      deck.current_version as current_version,
      (select count(*) from public.deck_versions version where version.deck_id = deck.id) as version_count,
      coalesce((
        select sum(card.quantity)::bigint
        from public.deck_versions version
        join public.deck_cards card on card.deck_version_id = version.id
        where version.deck_id = deck.id and version.version = deck.current_version
      ), 0) as total_cards,
      (select count(*) from public.post_decks attachment
        join public.deck_versions version on version.id = attachment.deck_version_id
        where version.deck_id = deck.id) as post_count,
      deck.created_at as created_at,
      deck.updated_at as updated_at,
      deck.archived_at as archived_at,
      deck.archive_reason as archive_reason
    from public.decks deck
    join public.profiles profile on profile.id = deck.owner_id
    join public.formats format on format.slug = deck.format
  ), filtered as (
    select * from deck_rows deck_row
    where (
      trim(coalesce(p_query, '')) = ''
      or deck_row.title ilike '%' || trim(p_query) || '%'
      or deck_row.owner_handle ilike '%' || trim(p_query) || '%'
      or deck_row.owner_name ilike '%' || trim(p_query) || '%'
    )
      and (p_format = 'all' or deck_row.format = p_format)
      and (
        p_state = 'all'
        or (p_state = 'active' and deck_row.archived_at is null and deck_row.moderation_status = 'visible')
        or (p_state = 'hidden' and deck_row.archived_at is null and deck_row.moderation_status = 'hidden')
        or (p_state = 'archived' and deck_row.archived_at is not null)
      )
  )
  select filtered.*, count(*) over() as total_count
  from filtered
  order by filtered.archived_at nulls first, filtered.updated_at desc, filtered.id
  limit least(greatest(p_limit, 1), 100)
  offset greatest(p_offset, 0);
end;
$$;

create function public.admin_create_deck(
  p_owner_id uuid,
  p_title text,
  p_format text,
  p_visibility public.deck_visibility,
  p_description text,
  p_note text,
  p_cards jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := (select auth.uid());
  new_deck_id uuid;
  new_version_id uuid;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if not exists (select 1 from public.profiles where id = p_owner_id) then raise exception 'Owner not found'; end if;
  perform public.validate_deck_card_payload(p_format, p_cards);

  insert into public.decks (owner_id, title, format, description, visibility)
  values (p_owner_id, trim(p_title), p_format, trim(coalesce(p_description, '')), p_visibility)
  returning decks.id into new_deck_id;
  insert into public.deck_versions (deck_id, version, note)
  values (new_deck_id, 1, trim(coalesce(p_note, '')))
  returning deck_versions.id into new_version_id;
  perform public.insert_deck_version_cards(new_version_id, p_cards);
  insert into public.deck_admin_audit_log (deck_id, actor_id, action, metadata)
  values (new_deck_id, actor, 'deck_created', jsonb_build_object('owner_id', p_owner_id, 'version_id', new_version_id));
  return new_deck_id;
end;
$$;

create function public.admin_create_deck_version(p_deck_id uuid, p_note text, p_cards jsonb)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := (select auth.uid());
  deck_row public.decks%rowtype;
  new_version integer;
  new_version_id uuid;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  select * into deck_row from public.decks where id = p_deck_id for update;
  if not found then raise exception 'Deck not found'; end if;
  if deck_row.archived_at is not null then raise exception 'Archived deck cannot receive versions'; end if;
  perform public.validate_deck_card_payload(deck_row.format, p_cards);
  select coalesce(max(version), 0) + 1 into new_version from public.deck_versions where deck_id = p_deck_id;
  insert into public.deck_versions (deck_id, version, note)
  values (p_deck_id, new_version, trim(coalesce(p_note, '')))
  returning id into new_version_id;
  perform public.insert_deck_version_cards(new_version_id, p_cards);
  update public.decks set current_version = new_version where id = p_deck_id;
  insert into public.deck_admin_audit_log (deck_id, actor_id, action, metadata)
  values (p_deck_id, actor, 'deck_version_created', jsonb_build_object('version', new_version, 'version_id', new_version_id));
  return new_version;
end;
$$;

create function public.admin_update_deck_metadata(
  p_deck_id uuid,
  p_title text,
  p_description text,
  p_visibility public.deck_visibility
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  update public.decks
  set title = trim(p_title), description = trim(coalesce(p_description, '')), visibility = p_visibility
  where id = p_deck_id;
  if not found then raise exception 'Deck not found'; end if;
  insert into public.deck_admin_audit_log (deck_id, actor_id, action)
  values (p_deck_id, (select auth.uid()), 'deck_metadata_updated');
end;
$$;

create function public.admin_transfer_deck(p_deck_id uuid, p_owner_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare previous_owner uuid;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if not exists (select 1 from public.profiles where id = p_owner_id) then raise exception 'Owner not found'; end if;
  select owner_id into previous_owner from public.decks where id = p_deck_id for update;
  if previous_owner is null then raise exception 'Deck not found'; end if;
  update public.decks set owner_id = p_owner_id where id = p_deck_id;
  insert into public.deck_admin_audit_log (deck_id, actor_id, action, metadata)
  values (p_deck_id, (select auth.uid()), 'deck_transferred', jsonb_build_object('from', previous_owner, 'to', p_owner_id));
end;
$$;

create function public.admin_set_deck_moderation(p_deck_id uuid, p_hidden boolean, p_reason text default '')
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := (select auth.uid());
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_hidden and char_length(trim(coalesce(p_reason, ''))) < 3 then raise exception 'Moderation reason required'; end if;
  update public.decks
  set moderation_status = (case when p_hidden then 'hidden' else 'visible' end)::public.deck_moderation_status,
      moderation_reason = case when p_hidden then trim(p_reason) else '' end,
      moderated_at = case when p_hidden then now() else null end,
      moderated_by = case when p_hidden then actor else null end
  where id = p_deck_id;
  if not found then raise exception 'Deck not found'; end if;
  insert into public.deck_admin_audit_log (deck_id, actor_id, action, reason)
  values (p_deck_id, actor, case when p_hidden then 'deck_hidden' else 'deck_restored' end, trim(coalesce(p_reason, '')));
end;
$$;

create function public.admin_set_deck_archived(p_deck_id uuid, p_archived boolean, p_reason text default '')
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := (select auth.uid());
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_archived and char_length(trim(coalesce(p_reason, ''))) < 3 then raise exception 'Archive reason required'; end if;
  update public.decks
  set archived_at = case when p_archived then now() else null end,
      archived_by = case when p_archived then actor else null end,
      archive_reason = case when p_archived then trim(p_reason) else '' end
  where id = p_deck_id;
  if not found then raise exception 'Deck not found'; end if;
  insert into public.deck_admin_audit_log (deck_id, actor_id, action, reason)
  values (p_deck_id, actor, case when p_archived then 'deck_archived' else 'deck_unarchived' end, trim(coalesce(p_reason, '')));
end;
$$;

create function public.delete_unreferenced_deck(p_deck_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := (select auth.uid());
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if not exists (select 1 from public.decks where id = p_deck_id and archived_at is not null for update) then
    raise exception 'Deck must be archived';
  end if;
  if exists (
    select 1 from public.post_decks attachment
    join public.deck_versions version on version.id = attachment.deck_version_id
    where version.deck_id = p_deck_id
  ) or exists (
    select 1 from public.archetypes archetype
    join public.deck_versions version on version.id = archetype.representative_version_id
    where version.deck_id = p_deck_id
  ) then raise exception 'Deck still has references'; end if;
  insert into public.deck_admin_audit_log (deck_id, actor_id, action)
  values (p_deck_id, actor, 'deck_deleted');
  delete from public.decks where id = p_deck_id;
end;
$$;

create or replace view public.deck_classification_candidates with (security_invoker = true) as
with normalized as (
  select v.id as version_id, c.zone, c.oracle_id, sum(c.quantity)::integer as quantity
  from public.decks d
  join public.formats f on f.slug = d.format
  join public.deck_versions v on v.deck_id = d.id and v.version = d.current_version
  join public.deck_cards c on c.deck_version_id = v.id
  where d.visibility = 'public' and d.moderation_status = 'visible' and d.archived_at is null
    and (c.zone = 'mainboard' or (f.commander_max > 0 and c.zone = 'commander'))
  group by v.id, c.zone, c.oracle_id
), signatures as (
  select version_id,
    coalesce(jsonb_object_agg(oracle_id::text, quantity) filter (where zone = 'mainboard' and oracle_id is not null), '{}'::jsonb) as main_cards,
    coalesce(jsonb_object_agg(oracle_id::text, quantity) filter (where zone = 'commander' and oracle_id is not null), '{}'::jsonb) as commander_cards,
    coalesce(sum(quantity) filter (where zone = 'mainboard'), 0) as main_count,
    coalesce(sum(quantity) filter (where zone = 'commander'), 0) as commander_count,
    bool_and(oracle_id is not null) as resolved
  from normalized group by version_id
)
select d.id as deck_id, v.id as version_id, d.title, d.format, d.created_at,
  s.main_cards, s.commander_cards, s.main_count, s.commander_count
from signatures s
join public.deck_versions v on v.id = s.version_id
join public.decks d on d.id = v.deck_id
join public.formats f on f.slug = d.format
where s.resolved
  and s.main_count >= f.mainboard_min
  and (f.mainboard_max is null or s.main_count <= f.mainboard_max)
  and s.commander_count >= f.commander_min
  and s.commander_count <= f.commander_max
  and s.main_count + s.commander_count >= f.total_min
  and (f.total_max is null or s.main_count + s.commander_count <= f.total_max);

create or replace view public.deck_library with (security_invoker = true) as
select d.id, d.title, d.format, d.description, d.visibility, d.current_version,
  d.updated_at, p.handle, p.display_name, v.id as version_id,
  coalesce(sum(c.quantity), 0)::integer as total_cards,
  (array_agg(c.image_small_url order by case when c.zone = 'commander' then 0 else 1 end, c.card_name)
    filter (where c.image_small_url is not null))[1] as cover_url,
  a.id as archetype_id, a.name as archetype_name, a.slug as archetype_slug,
  membership.similarity, f.name as format_name
from public.decks d
join public.formats f on f.slug = d.format
join public.profiles p on p.id = d.owner_id
left join public.deck_versions v on v.deck_id = d.id and v.version = d.current_version
left join public.deck_cards c on c.deck_version_id = v.id
left join public.deck_archetype_assignments membership on membership.deck_version_id = v.id
left join public.archetype_catalog a on a.id = membership.archetype_id and a.format = d.format
where d.moderation_status = 'visible' and d.archived_at is null
group by d.id, p.id, v.id, a.id, a.name, a.slug, membership.similarity, f.name;

revoke all on function public.validate_deck_card_payload(text, jsonb) from public, anon, authenticated;
revoke all on function public.insert_deck_version_cards(uuid, jsonb) from public, anon, authenticated;
revoke all on function public.get_admin_decks(text, text, text, integer, integer) from public, anon;
revoke all on function public.admin_create_deck(uuid, text, text, public.deck_visibility, text, text, jsonb) from public, anon;
revoke all on function public.admin_create_deck_version(uuid, text, jsonb) from public, anon;
revoke all on function public.admin_update_deck_metadata(uuid, text, text, public.deck_visibility) from public, anon;
revoke all on function public.admin_transfer_deck(uuid, uuid) from public, anon;
revoke all on function public.admin_set_deck_moderation(uuid, boolean, text) from public, anon;
revoke all on function public.admin_set_deck_archived(uuid, boolean, text) from public, anon;
revoke all on function public.delete_unreferenced_deck(uuid) from public, anon;

grant execute on function public.get_admin_decks(text, text, text, integer, integer) to authenticated;
grant execute on function public.admin_create_deck(uuid, text, text, public.deck_visibility, text, text, jsonb) to authenticated;
grant execute on function public.admin_create_deck_version(uuid, text, jsonb) to authenticated;
grant execute on function public.admin_update_deck_metadata(uuid, text, text, public.deck_visibility) to authenticated;
grant execute on function public.admin_transfer_deck(uuid, uuid) to authenticated;
grant execute on function public.admin_set_deck_moderation(uuid, boolean, text) to authenticated;
grant execute on function public.admin_set_deck_archived(uuid, boolean, text) to authenticated;
grant execute on function public.delete_unreferenced_deck(uuid) to authenticated;
