create extension if not exists citext with schema extensions;

create type public.post_visibility as enum ('public', 'followers', 'private');
create type public.deck_visibility as enum ('public', 'unlisted', 'private');
create type public.deck_zone as enum ('commander', 'mainboard', 'sideboard', 'maybeboard');
create type public.report_status as enum ('open', 'reviewing', 'resolved', 'dismissed');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  handle extensions.citext not null unique check (handle ~ '^[a-zA-Z0-9_]{3,30}$'),
  display_name text not null check (char_length(display_name) between 1 and 60),
  bio text not null default '' check (char_length(bio) <= 300),
  avatar_url text,
  favorite_formats text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  followed_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, followed_id),
  check (follower_id <> followed_id)
);

create table public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table public.mutes (
  muter_id uuid not null references public.profiles(id) on delete cascade,
  muted_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (muter_id, muted_id),
  check (muter_id <> muted_id)
);

create table public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 500),
  reply_to_id uuid references public.posts(id) on delete cascade,
  visibility public.post_visibility not null default 'public',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.post_likes (
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table public.reposts (
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table public.decks (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 100),
  format text not null check (format in ('commander', 'standard', 'modern', 'pioneer')),
  description text not null default '' check (char_length(description) <= 2000),
  visibility public.deck_visibility not null default 'public',
  current_version integer not null default 1 check (current_version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.deck_versions (
  id uuid primary key default gen_random_uuid(),
  deck_id uuid not null references public.decks(id) on delete cascade,
  version integer not null check (version >= 1),
  note text not null default '' check (char_length(note) <= 500),
  created_at timestamptz not null default now(),
  unique (deck_id, version)
);

create table public.deck_cards (
  id bigint generated by default as identity primary key,
  deck_version_id uuid not null references public.deck_versions(id) on delete cascade,
  zone public.deck_zone not null default 'mainboard',
  quantity smallint not null check (quantity between 1 and 100),
  oracle_id uuid,
  scryfall_id uuid not null,
  card_name text not null,
  image_small_url text,
  image_normal_url text,
  unique (deck_version_id, zone, scryfall_id)
);

create table public.post_decks (
  post_id uuid primary key references public.posts(id) on delete cascade,
  deck_version_id uuid not null references public.deck_versions(id) on delete restrict
);

create table public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  post_id uuid references public.posts(id) on delete cascade,
  reported_user_id uuid references public.profiles(id) on delete cascade,
  reason text not null check (char_length(reason) between 3 and 500),
  status public.report_status not null default 'open',
  created_at timestamptz not null default now(),
  check ((post_id is not null)::integer + (reported_user_id is not null)::integer = 1)
);

create index posts_author_created_idx on public.posts (author_id, created_at desc);
create index posts_created_idx on public.posts (created_at desc, id desc);
create index follows_followed_idx on public.follows (followed_id, follower_id);
create index decks_owner_updated_idx on public.decks (owner_id, updated_at desc);
create index deck_versions_deck_idx on public.deck_versions (deck_id, version desc);
create index deck_cards_version_zone_idx on public.deck_cards (deck_version_id, zone);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger posts_set_updated_at before update on public.posts
for each row execute function public.set_updated_at();
create trigger decks_set_updated_at before update on public.decks
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, handle, display_name)
  values (
    new.id,
    'mage_' || left(replace(new.id::text, '-', ''), 10),
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1), 'Nuevo mago')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.follows enable row level security;
alter table public.blocks enable row level security;
alter table public.mutes enable row level security;
alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
alter table public.reposts enable row level security;
alter table public.decks enable row level security;
alter table public.deck_versions enable row level security;
alter table public.deck_cards enable row level security;
alter table public.post_decks enable row level security;
alter table public.reports enable row level security;

create policy "profiles are public" on public.profiles for select using (true);
create policy "users update own profile" on public.profiles for update to authenticated
using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "follows are public" on public.follows for select using (true);
create policy "users create own follows" on public.follows for insert to authenticated
with check ((select auth.uid()) = follower_id);
create policy "users delete own follows" on public.follows for delete to authenticated
using ((select auth.uid()) = follower_id);

create policy "users view own blocks" on public.blocks for select to authenticated
using ((select auth.uid()) = blocker_id);
create policy "users create own blocks" on public.blocks for insert to authenticated
with check ((select auth.uid()) = blocker_id);
create policy "users delete own blocks" on public.blocks for delete to authenticated
using ((select auth.uid()) = blocker_id);

create policy "users view own mutes" on public.mutes for select to authenticated
using ((select auth.uid()) = muter_id);
create policy "users create own mutes" on public.mutes for insert to authenticated
with check ((select auth.uid()) = muter_id);
create policy "users delete own mutes" on public.mutes for delete to authenticated
using ((select auth.uid()) = muter_id);

create policy "visible posts can be read" on public.posts for select using (
  visibility = 'public'
  or author_id = (select auth.uid())
  or (
    visibility = 'followers'
    and exists (
      select 1 from public.follows
      where follower_id = (select auth.uid()) and followed_id = author_id
    )
  )
);
create policy "users create own posts" on public.posts for insert to authenticated
with check ((select auth.uid()) = author_id);
create policy "users update own posts" on public.posts for update to authenticated
using ((select auth.uid()) = author_id) with check ((select auth.uid()) = author_id);
create policy "users delete own posts" on public.posts for delete to authenticated
using ((select auth.uid()) = author_id);

create policy "post likes are readable" on public.post_likes for select using (true);
create policy "users create own likes" on public.post_likes for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy "users delete own likes" on public.post_likes for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "reposts are readable" on public.reposts for select using (true);
create policy "users create own reposts" on public.reposts for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy "users delete own reposts" on public.reposts for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "visible decks can be read" on public.decks for select using (
  visibility in ('public', 'unlisted') or owner_id = (select auth.uid())
);
create policy "users create own decks" on public.decks for insert to authenticated
with check ((select auth.uid()) = owner_id);
create policy "users update own decks" on public.decks for update to authenticated
using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy "users delete own decks" on public.decks for delete to authenticated
using ((select auth.uid()) = owner_id);

create policy "visible deck versions can be read" on public.deck_versions for select using (
  exists (
    select 1 from public.decks
    where decks.id = deck_versions.deck_id
      and (decks.visibility in ('public', 'unlisted') or decks.owner_id = (select auth.uid()))
  )
);
create policy "owners create deck versions" on public.deck_versions for insert to authenticated
with check (exists (select 1 from public.decks where decks.id = deck_id and decks.owner_id = (select auth.uid())));

create policy "visible deck cards can be read" on public.deck_cards for select using (
  exists (
    select 1 from public.deck_versions
    join public.decks on decks.id = deck_versions.deck_id
    where deck_versions.id = deck_cards.deck_version_id
      and (decks.visibility in ('public', 'unlisted') or decks.owner_id = (select auth.uid()))
  )
);
create policy "owners create deck cards" on public.deck_cards for insert to authenticated
with check (
  exists (
    select 1 from public.deck_versions
    join public.decks on decks.id = deck_versions.deck_id
    where deck_versions.id = deck_version_id and decks.owner_id = (select auth.uid())
  )
);

create policy "visible post decks can be read" on public.post_decks for select using (
  exists (select 1 from public.posts where posts.id = post_decks.post_id)
);
create policy "authors attach deck versions" on public.post_decks for insert to authenticated
with check (
  exists (select 1 from public.posts where posts.id = post_id and posts.author_id = (select auth.uid()))
  and exists (
    select 1 from public.deck_versions
    join public.decks on decks.id = deck_versions.deck_id
    where deck_versions.id = deck_version_id and decks.owner_id = (select auth.uid())
  )
);

create policy "users create reports" on public.reports for insert to authenticated
with check ((select auth.uid()) = reporter_id);
create policy "users view own reports" on public.reports for select to authenticated
using ((select auth.uid()) = reporter_id);

grant usage on schema public to anon, authenticated;
grant select on public.profiles, public.follows, public.posts, public.post_likes, public.reposts,
  public.decks, public.deck_versions, public.deck_cards, public.post_decks to anon, authenticated;
grant select on public.blocks, public.mutes, public.reports to authenticated;
grant insert, update, delete on public.profiles, public.follows, public.blocks, public.mutes,
  public.posts, public.post_likes, public.reposts, public.decks, public.deck_versions,
  public.deck_cards, public.post_decks, public.reports to authenticated;
grant usage, select on all sequences in schema public to authenticated;
